#!/bin/sh
SRC_SYSTEM=system
DST_SYSTEM=../system
cp -a ${SRC_SYSTEM}/bin/btmacreader ${DST_SYSTEM}/bin/btmacreader
cp -a ${SRC_SYSTEM}/bin/sensors-config ${DST_SYSTEM}/bin/sensors-config
cp -a ${SRC_SYSTEM}/bin/tf_daemon ${DST_SYSTEM}/bin/tf_daemon
cp -a ${SRC_SYSTEM}/etc/apns-conf.xml ${DST_SYSTEM}/etc/apns-conf.xml
cp -a ${SRC_SYSTEM}/etc/asound.conf ${DST_SYSTEM}/etc/asound.conf
cp -a ${SRC_SYSTEM}/etc/permissions/com.google.android.maps.xml ${DST_SYSTEM}/etc/permissions/com.google.android.maps.xml
cp -a ${SRC_SYSTEM}/etc/permissions/com.google.android.media.effects.xml ${DST_SYSTEM}/etc/permissions/com.google.android.media.effects.xml
cp -a ${SRC_SYSTEM}/etc/permissions/com.google.widevine.software.drm.xml ${DST_SYSTEM}/etc/permissions/com.google.widevine.software.drm.xml
cp -a ${SRC_SYSTEM}/etc/permissions/features.xml ${DST_SYSTEM}/etc/permissions/features.xml
cp -a ${SRC_SYSTEM}/etc/preferred-apps/google.xml ${DST_SYSTEM}/etc/preferred-apps/google.xml
cp -a ${SRC_SYSTEM}/etc/updatecmds/google_generic_update.txt ${DST_SYSTEM}/etc/updatecmds/google_generic_update.txt
cp -a ${SRC_SYSTEM}/lib/hw/camera.tegra3.so ${DST_SYSTEM}/lib/hw/camera.tegra3.so
cp -a ${SRC_SYSTEM}/lib/hw/sensors.grouper.so ${DST_SYSTEM}/lib/hw/sensors.grouper.so
cp -a ${SRC_SYSTEM}/lib/libEnjemailuri.so ${DST_SYSTEM}/lib/libEnjemailuri.so
cp -a ${SRC_SYSTEM}/lib/lib_dic_en_USUK.conf.so ${DST_SYSTEM}/lib/lib_dic_en_USUK.conf.so
cp -a ${SRC_SYSTEM}/lib/lib_dic_en_xlarge_USUK.conf.so ${DST_SYSTEM}/lib/lib_dic_en_xlarge_USUK.conf.so
cp -a ${SRC_SYSTEM}/lib/lib_dic_ja_JP.conf.so ${DST_SYSTEM}/lib/lib_dic_ja_JP.conf.so
cp -a ${SRC_SYSTEM}/lib/lib_dic_ja_xlarge_JP.conf.so ${DST_SYSTEM}/lib/lib_dic_ja_xlarge_JP.conf.so
cp -a ${SRC_SYSTEM}/lib/lib_dic_morphem_ja_JP.conf.so ${DST_SYSTEM}/lib/lib_dic_morphem_ja_JP.conf.so
cp -a ${SRC_SYSTEM}/lib/libchromeview.so ${DST_SYSTEM}/lib/libchromeview.so
cp -a ${SRC_SYSTEM}/lib/libearthmobile.so ${DST_SYSTEM}/lib/libearthmobile.so
cp -a ${SRC_SYSTEM}/lib/libennjcon.so ${DST_SYSTEM}/lib/libennjcon.so
cp -a ${SRC_SYSTEM}/lib/libennjubase1.so ${DST_SYSTEM}/lib/libennjubase1.so
cp -a ${SRC_SYSTEM}/lib/libennjubase1gb.so ${DST_SYSTEM}/lib/libennjubase1gb.so
cp -a ${SRC_SYSTEM}/lib/libennjubase1us.so ${DST_SYSTEM}/lib/libennjubase1us.so
cp -a ${SRC_SYSTEM}/lib/libennjubase2.so ${DST_SYSTEM}/lib/libennjubase2.so
cp -a ${SRC_SYSTEM}/lib/libennjubase3.so ${DST_SYSTEM}/lib/libennjubase3.so
cp -a ${SRC_SYSTEM}/lib/libennjyomi.so ${DST_SYSTEM}/lib/libennjyomi.so
cp -a ${SRC_SYSTEM}/lib/libfacelock_jni.so ${DST_SYSTEM}/lib/libfacelock_jni.so
cp -a ${SRC_SYSTEM}/lib/libfilterpack_facedetect.so ${DST_SYSTEM}/lib/libfilterpack_facedetect.so
cp -a ${SRC_SYSTEM}/lib/libfrsdk.so ${DST_SYSTEM}/lib/libfrsdk.so
cp -a ${SRC_SYSTEM}/lib/libgcomm_jni.so ${DST_SYSTEM}/lib/libgcomm_jni.so
cp -a ${SRC_SYSTEM}/lib/libgoogle_recognizer_jni.so ${DST_SYSTEM}/lib/libgoogle_recognizer_jni.so
cp -a ${SRC_SYSTEM}/lib/libiwnn.so ${DST_SYSTEM}/lib/libiwnn.so
cp -a ${SRC_SYSTEM}/lib/libjni_eglfence.so ${DST_SYSTEM}/lib/libjni_eglfence.so
cp -a ${SRC_SYSTEM}/lib/libjni_googlepinyinime.so ${DST_SYSTEM}/lib/libjni_googlepinyinime.so
cp -a ${SRC_SYSTEM}/lib/libjni_googlepinyinime_latinime.so ${DST_SYSTEM}/lib/libjni_googlepinyinime_latinime.so
cp -a ${SRC_SYSTEM}/lib/libjni_koreanime.so ${DST_SYSTEM}/lib/libjni_koreanime.so
cp -a ${SRC_SYSTEM}/lib/libjni_mosaic.so ${DST_SYSTEM}/lib/libjni_mosaic.so
cp -a ${SRC_SYSTEM}/lib/libkaomoji_kihon.so ${DST_SYSTEM}/lib/libkaomoji_kihon.so
cp -a ${SRC_SYSTEM}/lib/libkaomoji_tyukyu.so ${DST_SYSTEM}/lib/libkaomoji_tyukyu.so
cp -a ${SRC_SYSTEM}/lib/libnjaddress.so ${DST_SYSTEM}/lib/libnjaddress.so
cp -a ${SRC_SYSTEM}/lib/libnjcon.so ${DST_SYSTEM}/lib/libnjcon.so
cp -a ${SRC_SYSTEM}/lib/libnjemoji.so ${DST_SYSTEM}/lib/libnjemoji.so
cp -a ${SRC_SYSTEM}/lib/libnjexyomi.so ${DST_SYSTEM}/lib/libnjexyomi.so
cp -a ${SRC_SYSTEM}/lib/libnjfzk.so ${DST_SYSTEM}/lib/libnjfzk.so
cp -a ${SRC_SYSTEM}/lib/libnjname.so ${DST_SYSTEM}/lib/libnjname.so
cp -a ${SRC_SYSTEM}/lib/libnjtan.so ${DST_SYSTEM}/lib/libnjtan.so
cp -a ${SRC_SYSTEM}/lib/libnjubase1.so ${DST_SYSTEM}/lib/libnjubase1.so
cp -a ${SRC_SYSTEM}/lib/libnjubase2.so ${DST_SYSTEM}/lib/libnjubase2.so
cp -a ${SRC_SYSTEM}/lib/libnjubaseidx1.so ${DST_SYSTEM}/lib/libnjubaseidx1.so
cp -a ${SRC_SYSTEM}/lib/libnjubaseidx2.so ${DST_SYSTEM}/lib/libnjubaseidx2.so
cp -a ${SRC_SYSTEM}/lib/libpatts_engine_jni_api.so ${DST_SYSTEM}/lib/libpatts_engine_jni_api.so
cp -a ${SRC_SYSTEM}/lib/libsensors.lightsensor.so ${DST_SYSTEM}/lib/libsensors.lightsensor.so
cp -a ${SRC_SYSTEM}/lib/libspeexwrapper.so ${DST_SYSTEM}/lib/libspeexwrapper.so
cp -a ${SRC_SYSTEM}/lib/libvideochat_jni.so ${DST_SYSTEM}/lib/libvideochat_jni.so
cp -a ${SRC_SYSTEM}/lib/libvideochat_stabilize.so ${DST_SYSTEM}/lib/libvideochat_stabilize.so
cp -a ${SRC_SYSTEM}/lib/libvoicesearch.so ${DST_SYSTEM}/lib/libvoicesearch.so
cp -a ${SRC_SYSTEM}/lib/libvorbisencoder.so ${DST_SYSTEM}/lib/libvorbisencoder.so
cp -a ${SRC_SYSTEM}/media/LMprec_508.emd ${DST_SYSTEM}/media/LMprec_508.emd
cp -a ${SRC_SYSTEM}/media/PFFprec_600.emd ${DST_SYSTEM}/media/PFFprec_600.emd
cp -a ${SRC_SYSTEM}/media/bootanimation.zip ${DST_SYSTEM}/media/bootanimation.zip
cp -a ${SRC_SYSTEM}/media/video/AndroidInSpace.240p.mp4 ${DST_SYSTEM}/media/video/AndroidInSpace.240p.mp4
cp -a ${SRC_SYSTEM}/media/video/AndroidInSpace.480p.mp4 ${DST_SYSTEM}/media/video/AndroidInSpace.480p.mp4
cp -a ${SRC_SYSTEM}/media/video/Sunset.240p.mp4 ${DST_SYSTEM}/media/video/Sunset.240p.mp4
cp -a ${SRC_SYSTEM}/media/video/Sunset.480p.mp4 ${DST_SYSTEM}/media/video/Sunset.480p.mp4
cp -a ${SRC_SYSTEM}/usr/srec/en-US/lintrans_model ${DST_SYSTEM}/usr/srec/en-US/lintrans_model
cp -a ${SRC_SYSTEM}/usr/srec/en-US/ep_acoustic_model ${DST_SYSTEM}/usr/srec/en-US/ep_acoustic_model
cp -a ${SRC_SYSTEM}/usr/srec/en-US/google_hotword.config ${DST_SYSTEM}/usr/srec/en-US/google_hotword.config
cp -a ${SRC_SYSTEM}/usr/srec/en-US/g2p_fst ${DST_SYSTEM}/usr/srec/en-US/g2p_fst
cp -a ${SRC_SYSTEM}/usr/srec/en-US/normalizer ${DST_SYSTEM}/usr/srec/en-US/normalizer
cp -a ${SRC_SYSTEM}/usr/srec/en-US/hmmsyms ${DST_SYSTEM}/usr/srec/en-US/hmmsyms
cp -a ${SRC_SYSTEM}/usr/srec/en-US/norm_fst ${DST_SYSTEM}/usr/srec/en-US/norm_fst
cp -a ${SRC_SYSTEM}/usr/srec/en-US/google_hotword_clg ${DST_SYSTEM}/usr/srec/en-US/google_hotword_clg
cp -a ${SRC_SYSTEM}/usr/srec/en-US/embed_phone_nn_state_sym ${DST_SYSTEM}/usr/srec/en-US/embed_phone_nn_state_sym
cp -a ${SRC_SYSTEM}/usr/srec/en-US/contacts.abnf ${DST_SYSTEM}/usr/srec/en-US/contacts.abnf
cp -a ${SRC_SYSTEM}/usr/srec/en-US/compile_grammar.config ${DST_SYSTEM}/usr/srec/en-US/compile_grammar.config
cp -a ${SRC_SYSTEM}/usr/srec/en-US/acoustic_model ${DST_SYSTEM}/usr/srec/en-US/acoustic_model
cp -a ${SRC_SYSTEM}/usr/srec/en-US/phonelist ${DST_SYSTEM}/usr/srec/en-US/phonelist
cp -a ${SRC_SYSTEM}/usr/srec/en-US/endpointer_voicesearch.config ${DST_SYSTEM}/usr/srec/en-US/endpointer_voicesearch.config
cp -a ${SRC_SYSTEM}/usr/srec/en-US/dictation.config ${DST_SYSTEM}/usr/srec/en-US/dictation.config
cp -a ${SRC_SYSTEM}/usr/srec/en-US/grammar.config ${DST_SYSTEM}/usr/srec/en-US/grammar.config
cp -a ${SRC_SYSTEM}/usr/srec/en-US/hotword_symbols ${DST_SYSTEM}/usr/srec/en-US/hotword_symbols
cp -a ${SRC_SYSTEM}/usr/srec/en-US/offensive_word_normalizer ${DST_SYSTEM}/usr/srec/en-US/offensive_word_normalizer
cp -a ${SRC_SYSTEM}/usr/srec/en-US/c_fst ${DST_SYSTEM}/usr/srec/en-US/c_fst
cp -a ${SRC_SYSTEM}/usr/srec/en-US/clg ${DST_SYSTEM}/usr/srec/en-US/clg
cp -a ${SRC_SYSTEM}/usr/srec/en-US/rescoring_lm ${DST_SYSTEM}/usr/srec/en-US/rescoring_lm
cp -a ${SRC_SYSTEM}/usr/srec/en-US/metadata ${DST_SYSTEM}/usr/srec/en-US/metadata
cp -a ${SRC_SYSTEM}/usr/srec/en-US/embed_phone_nn_model ${DST_SYSTEM}/usr/srec/en-US/embed_phone_nn_model
cp -a ${SRC_SYSTEM}/usr/srec/en-US/symbols ${DST_SYSTEM}/usr/srec/en-US/symbols
cp -a ${SRC_SYSTEM}/usr/srec/en-US/dict ${DST_SYSTEM}/usr/srec/en-US/dict
cp -a ${SRC_SYSTEM}/usr/srec/en-US/endpointer_dictation.config ${DST_SYSTEM}/usr/srec/en-US/endpointer_dictation.config
cp -a ${SRC_SYSTEM}/usr/srec/en-US/google_hotword_logistic ${DST_SYSTEM}/usr/srec/en-US/google_hotword_logistic
cp -a ${SRC_SYSTEM}/vendor/lib/drm/libdrmwvmplugin.so ${DST_SYSTEM}/vendor/lib/drm/libdrmwvmplugin.so
cp -a ${SRC_SYSTEM}/vendor/lib/libwvm.so ${DST_SYSTEM}/vendor/lib/libwvm.so
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/nose_base-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/right_eye-y0-yi45-p0-pi45-r0-ri20.lg_32-2/full_model.bin
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/detection/multi_pose_face_landmark_detectors.7/left_eye-y0-yi45-p0-pi45-r0-ri20.lg_32/full_model.bin
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-r0-ri30.4a-v24/full_model.bin
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rn30-ri30.5-v24/full_model.bin
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/detection/yaw_roll_face_detectors.6/head-y0-yi45-p0-pi45-rp30-ri30.5-v24/full_model.bin
cp -a ${SRC_SYSTEM}/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin ${DST_SYSTEM}/vendor/pittpatt/models/recognition/face.face.y0-y0-22-b-N/full_model.bin

